name: nutrimate
description: "A simple nutrient tracking app with no signup/internet nonsense"
publish_to: 'none'
version: 1.1.0  # Incremented version number
versionCode: 2  # Incremented version code

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2

dev_dependencies: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
